"use client";

import { useState } from "react";
import {
  BarChart3, PieChart, TrendingUp, Users, FileText,
  Calendar, Download, ChevronRight, X, Filter
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { TiltCard } from "@/components/admin/TiltCard";
import { getReport } from "@/lib/admin-api";
import jsPDF from "jspdf";

// Report Types
const REPORT_TYPES = [
  {
    id: "income",
    title: "Income Report",
    icon: TrendingUp,
    description: "Revenue breakdown by client, project type, and payment mode.",
    color: "emerald"
  },
  {
    id: "expenses",
    title: "Expense Report",
    icon: PieChart,
    description: "Detailed cost analysis categorized by type and vendor.",
    color: "red"
  },
  {
    id: "profit_loss",
    title: "Profit & Loss",
    icon: BarChart3,
    description: "Net financial performance summary over selected periods.",
    color: "amber"
  },
  {
    id: "clients",
    title: "Client & Tax",
    icon: Users,
    description: "Client payment history, outstanding balances, and tax summaries.",
    color: "blue"
  }
];

export default function ReportsPage() {
  const [selectedReport, setSelectedReport] = useState<typeof REPORT_TYPES[0] | null>(null);
  const [dateRange, setDateRange] = useState({ start: "", end: "" });
  const [generating, setGenerating] = useState(false);



  const handleGenerate = async () => {
    if (!selectedReport || !dateRange.start || !dateRange.end) {
      alert("Please select a report type and date range.");
      return;
    }

    setGenerating(true);
    try {
      // 1. Fetch Data from Backend
      const result = await getReport(selectedReport.id, dateRange.start, dateRange.end);

      if (!result.success) {
        throw new Error(result.error || "Failed to generate report");
      }

      // 2. Generate PDF using jsPDF
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();

      // Header
      doc.setFontSize(22);
      doc.setTextColor(40, 40, 40);
      doc.text("SHIVKARA DIGITAL", pageWidth / 2, 20, { align: "center" });

      doc.setFontSize(16);
      doc.setTextColor(100, 100, 100);
      doc.text(selectedReport.title.toUpperCase(), pageWidth / 2, 30, { align: "center" });

      doc.setFontSize(12);
      doc.text(`Period: ${dateRange.start} to ${dateRange.end}`, pageWidth / 2, 40, { align: "center" });
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 46, { align: "center" });

      doc.line(20, 55, pageWidth - 20, 55);

      // Content (Simple Summary for now)
      let yPos = 70;
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text("Summary", 20, yPos);

      yPos += 15;
      doc.setFontSize(12);

      if (result.data.summary) {
        Object.entries(result.data.summary).forEach(([key, value]) => {
          doc.text(`${key.replace(/([A-Z])/g, ' $1').toUpperCase()}:`, 20, yPos);
          doc.text(`${value}`, 120, yPos);
          yPos += 10;
        });
      } else {
        doc.text("No summary data available for this report type.", 20, yPos);
      }

      // Footer
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text("Confidential Report - Generated by Shivkara Admin System", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

      // 3. Download
      doc.save(`${selectedReport.id}_report_${new Date().toISOString().split('T')[0]}.pdf`);

    } catch (error: any) {
      console.error("Report Generation Error:", error);
      alert(error.message);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="relative w-full min-h-screen text-white font-sans overflow-hidden perspective-1000">

      {/* Background Ambience - Amber/Orange Theme for Analytics */}
      <div className="fixed inset-0 z-0 bg-black">
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#222_1px,transparent_1px),linear-gradient(to_bottom,#222_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] opacity-20" />
        <div className="absolute top-[-20%] right-[30%] w-[60vw] h-[60vw] bg-amber-600/10 rounded-full blur-[150px] animate-pulse-slow" />
        <div className="absolute bottom-[-10%] left-[-10%] w-[40vw] h-[40vw] bg-orange-600/5 rounded-full blur-[100px] animate-pulse-slow delay-1000" />
      </div>

      <div className="relative z-10 max-w-[1400px] mx-auto p-6 md:p-8 space-y-12">

        {/* Header */}
        <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-8">
          <div className="relative">
            <div className="absolute -left-6 top-2 bottom-2 w-1 bg-gradient-to-b from-amber-500 to-transparent rounded-full opacity-50" />
            <motion.h1
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              className="text-5xl md:text-7xl font-black tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-white via-gray-200 to-gray-500 mb-2 filter drop-shadow-2xl"
            >
              REPORTS
            </motion.h1>
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
              className="text-gray-400 font-mono text-sm tracking-widest uppercase flex items-center gap-3"
            >
              <span className="w-2 h-2 bg-amber-500 rounded-full animate-pulse" />
              Intelligence Center
            </motion.p>
          </div>
        </div>

        {/* Report Selection Deck */}
        {!selectedReport && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {REPORT_TYPES.map((report, i) => (
              <motion.div
                key={report.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                onClick={() => setSelectedReport(report)}
                className="cursor-pointer"
              >
                <TiltCard className="h-full">
                  <div className={`h-full p-8 rounded-[2.5rem] bg-white/5 border border-white/10 backdrop-blur-xl relative overflow-hidden group hover:bg-white/10 transition-colors duration-500`}>
                    <div className={`absolute -right-8 -top-8 w-32 h-32 bg-${report.color}-500/20 rounded-full blur-3xl group-hover:bg-${report.color}-500/30 transition-all`} />

                    <div className="relative z-10 flex flex-col items-start gap-6 h-full">
                      <div className={`p-4 rounded-2xl bg-${report.color}-500/10 text-${report.color}-400 mb-2`}>
                        <report.icon size={32} />
                      </div>

                      <div>
                        <h3 className="text-2xl font-bold text-white mb-2">{report.title}</h3>
                        <p className="text-sm text-gray-400 leading-relaxed">{report.description}</p>
                      </div>

                      <div className="mt-auto pt-6 w-full flex items-center justify-between text-xs font-mono text-gray-500 uppercase tracking-widest group-hover:text-white transition-colors">
                        <span>Select</span>
                        <ChevronRight className="w-4 h-4" />
                      </div>
                    </div>
                  </div>
                </TiltCard>
              </motion.div>
            ))}
          </div>
        )}

        {/* Configuration Panel */}
        <AnimatePresence>
          {selectedReport && (
            <motion.div
              initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="relative p-1 rounded-[3rem] bg-gradient-to-b from-white/10 to-transparent"
            >
              <div className="rounded-[2.8rem] bg-[#0A0A0A] border border-white/5 p-8 md:p-12 relative overflow-hidden">

                {/* Close Button */}
                <button
                  onClick={() => setSelectedReport(null)}
                  className="absolute top-8 right-8 p-2 rounded-full bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white transition-all z-20"
                >
                  <X size={24} />
                </button>

                {/* Decoration */}
                <div className={`absolute top-0 right-0 w-[500px] h-[500px] bg-${selectedReport.color}-600/10 rounded-full blur-[120px] pointer-events-none`} />

                <div className="relative z-10 flex flex-col md:flex-row gap-12">

                  {/* Left Column: Info */}
                  <div className="w-full md:w-1/3 space-y-6">
                    <div className={`w-16 h-16 rounded-2xl bg-${selectedReport.color}-500/10 flex items-center justify-center text-${selectedReport.color}-400`}>
                      <selectedReport.icon size={32} />
                    </div>
                    <div>
                      <h2 className="text-4xl font-black text-white mb-2">{selectedReport.title}</h2>
                      <p className="text-gray-400 text-lg">{selectedReport.description}</p>
                    </div>

                    <div className="pt-8 border-t border-white/10">
                      <h4 className="text-sm font-bold text-gray-500 uppercase tracking-widest mb-4">Features</h4>
                      <ul className="space-y-3 text-gray-300">
                        <li className="flex items-center gap-3">
                          <div className={`w-1.5 h-1.5 rounded-full bg-${selectedReport.color}-500`} />
                          PDF Export
                        </li>
                        <li className="flex items-center gap-3">
                          <div className={`w-1.5 h-1.5 rounded-full bg-${selectedReport.color}-500`} />
                          Detailed CSV Data
                        </li>
                        <li className="flex items-center gap-3">
                          <div className={`w-1.5 h-1.5 rounded-full bg-${selectedReport.color}-500`} />
                          Visual Charts
                        </li>
                      </ul>
                    </div>
                  </div>

                  {/* Right Column: Configuration */}
                  <div className="w-full md:w-2/3 bg-white/5 rounded-[2rem] p-8 border border-white/5">
                    <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-3">
                      <Filter className="text-gray-400" size={20} />
                      Configure Report
                    </h3>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                      <div className="space-y-2">
                        <label className="text-xs font-bold text-gray-500 uppercase tracking-widest">Start Date</label>
                        <div className="relative">
                          <input
                            type="date"
                            className="w-full h-14 bg-black border border-white/10 rounded-xl px-4 text-white focus:border-amber-500 focus:outline-none transition-colors appearance-none"
                            value={dateRange.start}
                            onChange={(e) => setDateRange({ ...dateRange, start: e.target.value })}
                          />
                          <Calendar className="absolute right-4 top-4 text-gray-500 pointer-events-none" size={20} />
                        </div>
                      </div>

                      <div className="space-y-2">
                        <label className="text-xs font-bold text-gray-500 uppercase tracking-widest">End Date</label>
                        <div className="relative">
                          <input
                            type="date"
                            className="w-full h-14 bg-black border border-white/10 rounded-xl px-4 text-white focus:border-amber-500 focus:outline-none transition-colors appearance-none"
                            value={dateRange.end}
                            onChange={(e) => setDateRange({ ...dateRange, end: e.target.value })}
                          />
                          <Calendar className="absolute right-4 top-4 text-gray-500 pointer-events-none" size={20} />
                        </div>
                      </div>
                    </div>

                    <button
                      onClick={handleGenerate}
                      disabled={generating}
                      className={`w-full h-16 rounded-xl font-black text-lg flex items-center justify-center gap-3 shadow-2xl transition-all ${generating
                        ? "bg-gray-800 text-gray-500 cursor-not-allowed"
                        : `bg-gradient-to-r from-${selectedReport.color}-600 to-${selectedReport.color}-500 text-white hover:scale-[1.02] hover:shadow-${selectedReport.color}-500/25`
                        }`}
                    >
                      {generating ? (
                        "GENERATING..."
                      ) : (
                        <>
                          <Download size={24} />
                          GENERATE & DOWNLOAD
                        </>
                      )}
                    </button>

                  </div>

                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

      </div>
    </div>
  );
}
